### PR TITLE
Network JSON load

### LINKED ISSUE #102: Accept link to json file in query parameters
Partially resolves second use case of #101

### PR DESCRIPTION
**Pull request by pihart**
Resolves #102 

Deployed at https://pihart.github.io/qboard/ from https://github.com/pihart/qboard/commit/b69c9f342501f1114749bbd8f43f4739bb6e71b2

### CODE REVIEW

**Comment by pihart** [comment]
Resolves the non-hosting component of https://github.com/cjquines/qboard/issues/4#issuecomment-711097257 (unless this loading should be done server-side)

**Comment by pihart** [comment]
Question: should error names be hard-coded or handled cleanly and automatically like they are now:
https://github.com/cjquines/qboard/blob/28c8322dbcf0efde0d274de3edd04323d6049f4f/src/lib/error.ts#L1-L6

If cleanly then the minifier will have the ability to change the names in the production environment.

**Comment by cjquines** [comment]
don't think i want to add any network components to qboard yet

**Comment by pihart** [comment]
Please close this if you don't want it. I will then merge into `pihart:master`

**Comment by pihart** [comment]
Forgot to mention that the entire `error.ts` and `network.ts` can be imported from the minimal <https://github.com/pihart/ts>.

That means that the only changes in this PR are making the signatures in `files.ts` how they should have been from the start and this addition:
https://github.com/cjquines/qboard/blob/ccce2c134b2583dece985425bc881ce114ec49a4/src/lib/qboard.ts#L85-L89

---

Also "network" has always been used loosely; it just means initiating a standard (basic) client-slide GET request to a URL `iff` provided asked to do so by the user via query parameters

**Pull request closed without merging**
