### PR TITLE
Github Actions: Security Auditing and Linting

### PR DESCRIPTION
**Pull request by pihart**
* Security
  * Github CodeQL
  * ShiftLeft Scan
* Linting
  * wearerequired/lint-action

### CODE REVIEW

**Comment by cjquines** [comment]
wait sorry why is the security auditing necessary when we have things like dependabot

**Comment by pihart** [comment]
It [catches vulnerabilities *in* the code](https://securitylab.github.com/tools/codeql).

**Comment by pihart** [comment]
I'm confused. Stylelint is rejected but it [completes with no issues](https://github.com/pihart/qboard/runs/1387856654).

**Comment by cjquines** [comment]
its good to be confused™

**Comment by pihart** [comment]
Just wanted to make it clear that the security scan is important for catching xss vulnerabilities in the dependencies and in how we use them. dependabot differs in that it just listens for an npm vulnerability to be filed against package-lock.json. it is just an automated `npm audit fix`

as a trivial example, let's say we implement text (#76). then if fabric does something unsanitized, there is now an arbitrary code execution vulnerability, which, of course, gets exported to json. now this json file is a virus. note also that this gives an attacker free xsrf; to the user, the json file is running native code.

or considering something that's already been implemented, maybe this is the case with images (it shouldn't be unless fabric really sucks, but...). similarly, the build tools may be generating code that doesn't agree with the source code.

the scan also catches unexpected edge cases of things. i believe the github one also looks into concurrency issues.

the scans will also be helpful with #4 (both server- and client-side)

**Pull request merged**
