### PR TITLE
Use TS Strict Mode

### PR DESCRIPTION
**Pull request by pihart**
Strengthen many types and fix some errors

### CODE REVIEW

**Comment by cjquines** [comment]
if you're going to make 50+ commits to make this few changes i will squash these when i merge

**Comment by pihart** [comment]
I will rebase on my end

**Comment by pihart** [comment]
I lost some structure and it's not worth recovering it so just squash on accept

**Comment by pihart** [comment]
I don't know what's supposed to happen in StyleMenu.tsx.

Other than that, everything works

**Comment by pihart** [comment]
Please resolve this:
https://github.com/cjquines/qboard/blob/b7b029adadeae05addc618366d1ce9a35ffa46dc/src/components/Stylebar.tsx#L47-L48

I didn't assert as non-null because I didn't know whether that was actually true

**Comment by pihart** [comment]
All concerns have been resolved, this is ready

**Comment by cjquines** [comment]
i assume you want this after #106?

**Comment by pihart** [comment]
That would probably make it easier to resolve conflicts (this will be squashed), so yes.

**Comment by cjquines** [comment]
this has a lot of painful merge conflicts so i dont want to look at this yet

**Pull request merged**
